alpha: 0.25
backbone: timm_efficientnet_b1
da_brightness_magnitude: 0.0
da_contrast_magnitude: 0.0
df_path: catalogues/2025_08_19_s2_l2a_16d.pkl
epoch_start_scheduler: 10
fold_nb: 3
gpu_da_params:
- 0.25
input_channel: 13
lr: 0.001
model: unetplusplus
n_epochs: 1000
name: Exp_S2_l2a_16d_1-3
num_batches: 15
num_classes: 1
only_val: false
patience: 8
pretrained: noisy-student
print_freq: 500
random_sized_params:
- 0.0
- 0.0
randomsizecrop_interpolation: 1
resume: ''
train_batch_size: 16
train_crop_size: 320
use_fp16: 0
val_batch_size: 32
weight_decay: 0.0
